name: CI/CD for HTML Page

on:
  push:
    branches:
      - main  # Ensure this matches your branch name

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-files
          path: |
            index.html  # Ensure index.html is in the root directory

  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for deployment to GitHub Pages
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download HTML Artifact
        uses: actions/download-artifact@v3
        with:
          name: html-files
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.dppp }}  # Default GitHub token for authentication
          publish_dir: ./public  # Ensure this matches the downloaded artifact path
