name: CI/CD for HTML Page

on:
  push:
    branches:
      - master

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # Assuming you don't have any dependencies for a basic HTML page, we can skip this step.

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: html-file
          path: |
            ./index.html

  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: html-file
          path: ./html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_KEY }}  # Use the default GitHub token for authentication
          publish_dir: ./html
